config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'
  get 'pages/attendance'
  get 'pages/ledger'
  get 'pages/marks'
  devise_scope :user do
    root to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/accomodation_info.rb
# == Schema Information
#
# Table name: accomodation_infos
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  hostel_name  :string
#  room_number  :integer
#  floor_number :string
#  food         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class AccomodationInfo < ActiveRecord::Base
  belongs_to :user
end

app/models/admission_info.rb
# == Schema Information
#
# Table name: admission_infos
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  category    :string
#  religion    :string
#  father_name :string
#  branch      :string
#  phone       :string
#  address     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class AdmissionInfo < ActiveRecord::Base
  belongs_to :user
end

app/models/attendance.rb
# == Schema Information
#
# Table name: attendances
#
#  id           :integer          not null, primary key
#  subject_name :string
#  status       :string
#  from         :string
#  to           :string
#  day          :datetime
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Attendance < ActiveRecord::Base
  belongs_to :user
end

app/models/ledger_info.rb
# == Schema Information
#
# Table name: ledger_infos
#
#  id           :integer          not null, primary key
#  doc_no       :string
#  release_date :date
#  narration    :string
#  status       :string
#  amount       :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer
#

class LedgerInfo < ActiveRecord::Base
  belongs_to :user
end

app/models/marks_info.rb
# == Schema Information
#
# Table name: marks_infos
#
#  id             :integer          not null, primary key
#  max_marks      :string
#  min_marks      :string
#  marks_obtained :string
#  user_id        :integer
#  branch         :string
#  semister       :string
#  exam_type      :string
#  subject        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class MarksInfo < ActiveRecord::Base
  belongs_to :user
end

app/models/personal_info.rb
# == Schema Information
#
# Table name: personal_infos
#
#  id          :integer          not null, primary key
#  usn         :string
#  course      :string
#  semister    :string
#  nationality :string
#  state       :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class PersonalInfo < ActiveRecord::Base
  belongs_to :user
end

app/models/transport_info.rb
# == Schema Information
#
# Table name: transport_infos
#
#  id              :integer          not null, primary key
#  route           :string
#  pickup_location :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#

class TransportInfo < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  date_of_birth          :date
#  blood_group            :string
#  campus_id              :string
#  opening_balance        :string
#  parent_id              :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         authentication_keys: [:login]
  validates :campus_id, uniqueness: true
  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.campus_id || self.email
  end

  has_one :child, class_name: 'User',
                      foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'User'

  has_one :personal_info, dependent: :destroy
  delegate :usn, :course, :semister, :nationality, :state, to: :personal_info, allow_nil: true

  has_one :admission_info, dependent: :destroy
  delegate :category, :religion, :father_name, :branch, :phone, :address, to: :admission_info, allow_nil: true

  has_one :accomodation_info, dependent: :destroy
  delegate :hostel_name, :room_number, :floor_number, :food, to: :accomodation_info, allow_nil: true

  has_one :transport_info, dependent: :destroy
  delegate :route, :pickup_location, to: :transport_info, allow_nil: true

  has_many :ledger_infos, dependent: :destroy
  has_many :marks_infos, dependent: :destroy
  has_many :attendances, dependent: :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      User.find_by(email: login) || User.find_by(campus_id: login)
    else
      if conditions[:campus_id].nil?
        where(conditions).first
      else
        where(campus_id: conditions[:campus_id]).first
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || pages_index_path
  end
  
  protected

  def configure_permitted_parameters
    added_attrs = [:campus_id, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.for(:sign_up) << added_attrs
    devise_parameter_sanitizer.for(:account_update) << added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'will_paginate/array'

  def index
  end

  def marks
  	if params[:exam_type]
  		if current_user.child.present? 
      	@marks = current_user.child.marks_infos.where('exam_type = ? and semister = ?', params["exam_type"], params["semister"])
    	else
    		@marks = current_user.marks_infos.where('exam_type = ? and semister = ?', params["exam_type"], params["semister"])
    	end
    end
  end

  def attendance
    if params[:from].present?
      from, to = Date.strptime(params[:from], '%m/%d/%Y'), Date.strptime(params[:to], '%m/%d/%Y')
      arr = (from..to).to_a
      if current_user.child.present? 
        @attendances = Attendance.where(user_id: current_user.child.id).where(day: arr).group_by { |a| a.day }
      else
        @attendances = Attendance.where(user_id: current_user.id).where(day: arr).group_by { |a| a.day }
      end
    else
      if current_user.child.present?
        @attendances = Attendance.where(user_id: current_user.child.id).group_by { |a| a.day }
      else
        @attendances = Attendance.where(user_id: current_user.id).group_by { |a| a.day }
      end
    end
    params[:sem] = 'I' if params[:sem].blank?
    @attendances_search = current_user.attendances.where(sem: params[:sem]).group_by { |a| a.subject_name }
    @total_classes = current_user.attendances.where(sem: params[:sem]).group_by { |a| a.subject_name }
    @classes_present = current_user.attendances.where(sem: params[:sem], status: "P").group_by { |a| a.subject_name }
    @classes_absent = current_user.attendances.where(sem: params[:sem], status: "A").group_by { |a| a.subject_name }
    @attendances_keys = @attendances.keys.sort.reverse.paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

	def internals
		array = ['INTERNAL 1', 'INTERNAL 2', 'INTERNAL 3', 'EXTERNAL']
		return array
	end

	def semister
		array = %w(I II III IV V VI VII VIII)
		return array
	end
end

app/views/layouts/_header.html.erb
<div class="basic-info">
  <div class="animated fadeInDown">
    <div class="col-md-12 header-band">
      <div class="dropdown pull-right">
        <span><%= current_user.name %></span>
        <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
          <span class="dots"></span>
          <span class="dots"></span>
          <span class="dots"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="<%= edit_user_registration_path %>">Change Password</a></li>
          <li><a href="<%= users_sign_out_path %>">Logout</a></li>
        </div>
      </ul>
    </div>
    <div class="clearfix"></div>
    <header id="nav">
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <!-- <a class="navbar-brand"><%= image_tag 'logo.png', :class => 'img-responsive' %></a> -->
            <%= link_to( image_tag("logo.png", :class => 'logo'), pages_index_path, :class=>"img-responsive navbar-brand") %>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="<%= pages_index_path %>"> <i class="ico" aria-hidden="true" data-icon="&#xe107;"></i> Info. </a> </li>
              <li><a href="<%= pages_attendance_path %>"> <i class="ico" aria-hidden="true" data-icon="&#xe06b;"></i> Attendance. </a></li>
              <li><a href="<%= pages_marks_path %>"> <i class="ico" aria-hidden="true" data-icon="&#xe029;"></i> Marks. </a></li>
              <li><a href="<%= pages_ledger_path %>"> <i class="ico" aria-hidden="true" data-icon="&#x68;"></i> Ledger. </a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html><!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""><![endif]--><!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang=""><![endif]--><!--[if IE 8]><html class="no-js lt-ie9" lang=""><![endif]--><!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]--><head>
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" /><meta name="description" content="">
<meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Yenepoya Institute of Technology</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <link rel="stylesheet" type="text/css" href="/assets/fonts.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,700,300,300,100' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700,300' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user.present?  %>
      <%= render partial: '/layouts/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/attendance.html.erb
<% if current_user.child.present? %>
  <% user = current_user.child %>
<% else %>
  <% user = current_user %>
<% end %>
<div class="attendance">
  <div class="container-fluid">
    <div class="container animated fadeIn">
      <div class="form-wrap">
        <%= form_tag(pages_attendance_path, :method => "get", id: "search-form") do %>
          <div class="input-wrap col-md-4">
            <%= text_field_tag 'from', params[:from], :class => "input-element date-picker" %>
            <span class="highlight"></span>
            <span class="bar"></span>
          </div>
          <div class="input-wrap col-md-4">
            <%= text_field_tag 'to', params[:to], :class => "input-element date-picker" %>
          </div>
          <div class="col-md-4">
            <%= submit_tag "Load", class: "btn btn-primary" %>
          </div>
        <% end %>
        <div class="clearfix"></div>
        <div class="col-md-12 attendance-grid">
          <ul class="list-inline">
            <li><i class="legend1"></i>Present</li>
            <li><i class="legend2"></i>Absent</li>
          </ul>
          <div class="clearfix"></div>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>DATE</th>
                  <th colspan="8">SUBJECTS</th>
                </tr>
              </thead>
              <tbody>
                <% if @attendances.values.flatten.count > 0 %>
                  <% @attendances_keys.each do |k| %>
                    <% @attendances[k].group_by { |a| a.day }.each do |k, v| %>
                      <tr>
                        <td><%= k.to_date.strftime('%d/%m/%Y') %></td>
                        <% v.sort_by { |a| Time.strptime(a.from, '%I:%M %p') }.each do |a| %>
                          <% if a.status == "A" %>
                            <td class="absent">
                            <% else %>
                              <td>
                              <% end %>
                              <p><%= a.from %> - <%= a.to %></p>
                              <p><%= a.subject_name %></p>
                            </td>
                          <% end %>
                          <% (@attendances.map { |k, v| v.count }.max - v.count).times do |i| %>
                            <td>
                              <p>-</p>
                            </td>
                          <% end %>
                        </tr>
                      <% end %>
                    <% end %>
                  <% else %>
                    <tr>
                      <td></td>
                      <td></td>
                      <td align="center">No Results Found</td>
                      <td></td>
                      <td></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              
            </div>
            <%= will_paginate @attendances_keys, :class => "pull-right pagination" %>
          </div>
        </div>
      </div>
      <div class="container animated fadeIn mt-x">
        <div class="form-wrap">
          <%= form_tag(pages_attendance_path, :method => "get", id: "search-form") do %>
            <div class="col-md-4">
              <%= select_tag 'sem', options_for_select(semister, :selected => params[:sem]), { class: 'selectpicker chosen-select' } %>
            </div>
            <div class="col-md-4">
              <%= submit_tag "Load", class: "btn btn-primary" %>
            </div>
          <% end %>
          <div class="col-md-12 marks-grid">
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>SUBJECT</th>
                    <th>TOTAL CLASSES</th>
                    <th>ABSENT</th>
                    <th>PRESENT</th>
                    <th>AVERAGE</th>
                  </tr>
                </thead><br/><br/>
                <tbody>
                  <% if @attendances_search.present? %>
                    <% @attendances_search.each do |k, v| %>
                      <tr>
                        <td><%= k %></td>
                        <td><%= @total_classes[k].count %></td>
                        <td><%= @classes_absent[k].count rescue 0 %></td>
                        <td><%= @classes_present[k].count rescue 0 %></td>
                        <td><%= ((@classes_present[k].count.to_f / @total_classes[k].count.to_f) * 100).round(2) %>%</td>
                      </tr>
                    <% end %>
                  <% else %>
                    <tr>
                      <td></td>
                      <td></td>
                      <td>No Results Found</td>
                      <td></td>
                      <td></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
      $('.nav li:nth-child(2)').addClass('active');
    });
</script>

app/views/pages/index.html.erb
<% if current_user.child.present? %>
  <% user = current_user.child %>
<% else %>
  <% user = current_user %>
<% end %>
<div class="container-fluid">
  <div class="container">
    <div class="col-md-2 col-sm-3 animated fadeInLeft s-profile">
      <%= image_tag 'photo.jpg', :class => "img-responsive"  %>
      <div class="col-md-12">
        <label>Name</label>
        <p><%= user.name %></p>
        <label>D.O.B</label>
        <p><%= user.date_of_birth %></p>
        <label>Email</label>
        <p><%= user.parent.present? ? user.parent.email : user.email %></p>
        <label>Blood Group</label>
        <p><%= user.blood_group %></p>
        <a href="<%= edit_user_registration_path %>" class="btn btn-primary btn-block">Change Password</a>
      </div>
    </div>
    <div class="col-md-10 col-sm-9 animated fadeInRight s-info">
      <div class="col-md-12">
        <ul>
          <li>
            <div class="col-md-6">
              <label>USN</label>
              <p><%= user.usn %></p>
            </div>
            <div class="col-md-6">
              <label>Campus ID</label>
              <p><%= user.campus_id %></p>
            </div>
            <div class="clearfix"></div>
          </li>
          <li>
            <div class="col-md-6">
              <label>Course</label>
              <p><%= user.course %></p>
            </div>
            <div class="col-md-6">
              <label>Semister</label>
              <p><%= user.semister %><sup><%= user.semister.to_i.ordinalize[1..-1].upcase %></sup></p>
            </div>
            <div class="clearfix"></div>
          </li>
          <li>
            <div class="col-md-6">
              <label>Nationality</label>
              <p><%= user.nationality %></p>
            </div>
            <div class="col-md-6">
              <label>State</label>
              <p><%= user.state.present? ? user.state : '-' %></p>
            </div>
            <div class="clearfix"></div>
          </li>
        </ul>
      </div>
      <div class="col-md-12">
        <h2>Addmission info.</h2>
        <ul>
          <li>
            <div class="col-md-6">
              <label>Category</label>
              <p><%= user.category.present? ? user.category : '-' %></p>
            </div>
            <div class="col-md-6">
              <label>Religion</label>
              <p><%= user.religion %></p>
            </div>
            <div class="clearfix"></div>
          </li>
          <li>
            <div class="col-md-6">
              <label>Father Name</label>
              <p><%= user.father_name %></p>
            </div>
            <div class="col-md-6">
              <label>Branch</label>
              <p><%= user.branch %></p>
            </div>
            <div class="clearfix"></div>
          </li>
          <li>
            <div class="col-md-6">
              <label>Email</label>
              <p><%= user.email %></p>
            </div>
            <div class="col-md-6">
              <label>Phone</label>
              <p><%= user.phone.present? ? user.phone : '-' %></p>
            </div>
            <div class="clearfix"></div>
          </li>
          <li>
            <div class="col-md-12">
              <label>Address</label>
              <p><%= user.address %></p>
              <!-- <p>Surathkal</p>
							<p>10435 Mangalore</p>
							<p>India</p> -->
            </div>
            <div class="clearfix"></div>
          </li>
        </ul>
      </div>
      <div class="col-md-12">
        <h2>Accomodation</h2>
        <ul>
          <li>
            <div class="col-md-6">
              <label>HOSTEL NAME </label>
              <p><%= user.hostel_name.present? ? user.hostel_name : '-' %></p>
            </div>
            <div class="col-md-6">
              <label>Floor No.</label>
              <p><%= user.floor_number.present? ? user.floor_number : '-' %></p>
            </div>
            <div class="clearfix"></div>
          </li>
          <li>
            <div class="col-md-6">
              <label>Room No.</label>
              <p><%= user.room_number.present? ? user.room_number : '-' %></p>
            </div>
            <div class="col-md-6">
              <label>Mess</label>
              <p><%= user.food.present? ? user.food : '-' %></p>
            </div>
            <div class="clearfix"></div>
          </li>
        </ul>
      </div>
      <div class="col-md-12">
        <h2>Transport</h2>
        <ul>
          <li>
            <div class="col-md-6">
              <label>Route</label>
              <p><%= user.route.present? ? user.route : '-' %></p>
            </div>
            <div class="col-md-6">
              <label>Pickup Location</label>
              <p><%= user.pickup_location.present? ? user.pickup_location : '-' %></p>
            </div>
            <div class="clearfix"></div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('.nav li:nth-child(1)').addClass('active');
  });
</script>

app/views/pages/ledger.html.erb
<% if current_user.child.present? %>
  <% user = current_user.child %>
<% else %>
  <% user = current_user %>
<% end %>
<div class="ledger">
  <div class="container-fluid">
    <div class="container animated fadeIn">
      <div class="col-md-12 legder-grid attendance-grid">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Sl No.</th>
                <th>Date</th>
                <th>Doc No.</th>
                <th>Narration</th>
                <th>Debit</th>
                <th>Credit</th>
                <th>Balance</th>
                <th>DR/CR</th>
              </tr>
            </thead>
            <tbody>
              <td></td>
              <td></td>
              <td></td>
              <td>Opening Balance</td>
              <td><%= user.opening_balance.to_i.abs > 0.00 ? '%.2f' % user.opening_balance.to_f.abs : "" %></td>
              <td><%= user.opening_balance.to_f <= 0 ? user.opening_balance.to_f.abs : "" %></td>
              <td></td>
              <td></td>
              <% user.ledger_infos.each.with_index(1) do |ledger_info, index| %>
                <tr>
                  <td><%= index %></td>
                  <td><%= ledger_info.release_date.strftime('%d/%m/%Y') %></td>
                  <td><%= ledger_info.doc_no %></td>
                  <td><%= ledger_info.narration %></td>
                  <td><%= ledger_info.status == "Dr" ? '%.2f' % ledger_info.amount : "-" %></td>
                  <td><%= ledger_info.status == "Cr" ? '%.2f' % ledger_info.amount : "-" %></td>
                  <td>
                    <%= "%.2f" % ((index == 1 ? ("%.2f" % (user.opening_balance.to_f + (ledger_info.status == "Dr" ? (ledger_info.amount.to_f) : (-ledger_info.amount.to_f )))) : ("%.2f" % (user.opening_balance.to_f.abs + user.ledger_infos.first(index).select {|l| l if l.status == "Dr"}.map(&:amount).map(&:to_f).sum - user.ledger_infos.first(index).select {|l| l if l.status == "Cr"}.map(&:amount).map(&:to_f).sum))).to_f.abs) %></td>
                  <% unless (index == 1 || index == user.ledger_infos.count) %>
                    <td><%= ledger_info.status %></td>
                  <% else %>
                    <td></td>
                  <% end %>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td><%= '%.2f' % ((user.opening_balance.to_i.abs > 0.00 ? user.opening_balance.to_f.abs : 0.00) + user.ledger_infos.where('status = ?', 'Dr').map(&:amount).map(&:to_i).sum) %></td>
                <td><%= '%.2f' % (user.opening_balance.to_f <= 0 ? user.opening_balance.to_f.abs :  + user.ledger_infos.where('status = ?', 'Cr').map(&:amount).map(&:to_i).sum) %></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('.nav li:nth-child(4)').addClass('active');
  });
</script>

app/views/pages/marks.html.erb
<div class="marks">
  <div class="container-fluid">
    <div class="container animated fadeIn">
      <div class="form-wrap">
        <%= form_tag(pages_marks_path, :method => "get", id: "search-form") do %>
          <div class="col-md-4">
            <%= select_tag 'exam_type', options_for_select(internals, :selected => params[:exam_type]), {class: 'selectpicker chosen-select'} %>
          </div>
          <div class="col-md-4">
            <%= select_tag 'semister', options_for_select(semister, :selected => params[:semister]), {class: 'selectpicker chosen-select'} %>
          </div>
          <div class="col-md-4">
            <%= submit_tag "Load", class: "btn btn-primary" %>
          </div>
        <% end %>
        <div class="col-md-12 marks-grid">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Subject</th>
                  <th>Max</th>
                  <th>Obtained</th>
                </tr>
              </thead>
              <tbody>
                <% if @marks.present? %>
                  <% @marks.each do |marks_info| %>
                    <tr>
                      <td><%= marks_info.subject %></td>
                      <td><%= marks_info.max_marks %></td>
                      <td><%= marks_info.marks_obtained %></td>
                    </tr>
                  <% end %>
                  <tfoot>
                    <tr>
                      <td>Total</td>
                      <td><%= current_user.marks_infos.where('exam_type = ? and semister = ?', params["exam_type"], params["semister"]).pluck(:max_marks).map(&:to_i).inject(:+) %></td>
                      <td><%= current_user.marks_infos.where('exam_type = ? and semister = ?', params["exam_type"], params["semister"]).pluck(:marks_obtained).map(&:to_i).inject(:+) %></td>
                    </tr>
                  </tfoot>
                <% else %>                 
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('.nav li:nth-child(3)').addClass('active');
  });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>